export const GAME_CONFIG = {
  player: {
    health: 100,
    forwardSpeed: 7.2,
    strafeSpeed: 6.8,
    backwardSpeed: 6.2,
    groundAcceleration: 40,
    groundDeceleration: 48,
    standingHeight: 1.7,
    cameraFovDegrees: 80,
    jumpInitialVelocity: 5.6,
    gravity: -24,
    airControlMultiplier: 0.3,
    airDeceleration: 10,
    jumpBufferSeconds: 0.14,
  },
  camera: { sensitivity: 0.0012, minSensitivity: 0.0006, maxSensitivity: 0.003, verticalLimit: 1.5 },
  weapon: {
    damage: 12.5,
    magazineSize: 30,
    roundsPerMinute: 600,
    reloadMs: 2200,
    range: 80,
    recoilPerShot: 0.006,
    hipSpread: 0.012,
  },
  regeneration: { delayMs: 2000, healthPerSecond: 20 },
  matchDurationSeconds: 300,
  bot: {
    count: 10,
    detectionRange: 30,
    fieldOfViewRadians: 1.85,
    perceptionSeconds: 0.2,
    decisionSeconds: 0.65,
    reactionSeconds: 0.32,
    accuracy: 0.5,
    personalSpace: 2.2,
  },
} as const;
